alias l "exa -l --icons --color=always --group-directories-first"
alias ls "exa --icons --color=always --group-directories-first"
alias lls "exa --icons --color=always --group-directories-first"
alias ll "exa -al --icons --color=always --group-directories-first"
alias la "exa -a --icons --color=always --group-directories-first"
alias lt "exa -aT --icons --color=always --group-directories-first"
alias l1 "exa -1 --icons --color=always --group-directories-first"
alias lr "exa -R --icons --color=always --group-directories-first"
alias ld "exa --icons --color=always --only-dirs"
alias lg "exa --icons --color=always --git-ignore"
alias l. "exa -a | egrep '^\.'"
alias tree "exa --tree --icons --color=always"
