alias l "eza -l --icons --color=always --group-directories-first"
alias ls "eza --icons --color=always --group-directories-first"
alias lls "eza --icons --color=always --group-directories-first"
alias ll "eza -al --icons --color=always --group-directories-first"
alias la "eza -a --icons --color=always --group-directories-first"
alias lt "eza -aT --icons --color=always --group-directories-first"
alias l1 "eza -1 --icons --color=always --group-directories-first"
alias lr "eza -R --icons --color=always --group-directories-first"
alias ld "eza --icons --color=always --only-dirs"
alias lg "eza --icons --color=always --git-ignore"
alias l. "eza -a | egrep '^\.'"
alias tree "eza --tree --icons --color=always"
