alias glod "git log --oneline -- $argv"
alias glodp "git log -p -- $argv"
alias glods "git log --stat -- $argv"
alias gcommitsnew "git log --oneline | nl"
alias gcommitssold "git log --oneline --reverse | nl"
