alias nix-channel-update "nix-channel --update"
alias nix-channel-update-root "sudo nix-channel --update"
alias nix-gc "nix-collect-garbage -d"
alias nix-gc-root "sudo nix-collect-garbage -d"
alias nixos-rebuild-switch "sudo nixos-rebuild switch"
alias nixos-rebuild-switch-upgrade "sudo nixos-rebuild switch --upgrade"
