alias pj "pijul"
alias pjpush "pj push"
alias pjpull "pj pull"
alias pjclone "pj clone"
alias pjadd "pj add"
alias pjrm "pj rm"
alias pjmv "pj mv"
alias pjst "pj status"
alias pjstv "pj status --verbose"
alias pjstc "pj status --changes"
alias pjstcv "pj status --changes --verbose"
alias pjstf "pj status --files"
alias pjstfv "pj status --files --verbose"
alias pjstt "pj status --tracked"
alias pjsttv "pj status --tracked --verbose"
alias pjstn "pj status --new"
alias pjstnv "pj status --new --verbose"
alias pjl "pj log"
alias pjlv "pj log --description"
alias pjshow "pj change"
alias pjs "pj diff -s"
alias pjd "pj diff"
alias pjkeygen "pj key generate `whoami`"
alias pjconfrm "echo 'warning: This will erase your pijul config and keys'; rm -ri \"$PIJULCONFDIR\""
alias pjrec "pj record -a -m"
alias pjamend "pj record -a --amend"