alias dmesg "dmesg --color=always | less"
alias kernel "uname -r"
alias cpuinfo "lscpu"
alias meminfo "free -h"
alias diskinfo "df -h"
alias uname "uname -a"
alias dfusage "du -sh *"
alias sizeof "du -hs"
alias filesize "du -sh"
alias uptime "uptime -p"
alias mounts "mount | column -t"
alias users "who | cut -d' ' -f1 | sort | uniq"
alias disks "lsblk -o HOTPLUG,NAME,SIZE,MODEL,TYPE | awk 'NR == 1 || /disk/'"
alias partitions "lsblk -o HOTPLUG,NAME,LABEL,MOUNTPOINT,SIZE,MODEL,PARTLABEL,TYPE,UUID"

alias mkfile "touch"