alias ytdlp "yt-dlp"
alias youtube-dl "yt-dlp"
alias yt-dl "yt-dlp"
alias ytdl "yt-dlp"
alias yt-subs "yt-dlp --list-subs"
alias yt-audio "yt-dlp -x --audio-format best"
alias yt-noaudio "yt-dlp -x --audio-format none"
alias yt-playlist "yt-dlp -x --audio-format best --yes-playlist"
alias yt-video "yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'"
alias yt-best "yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' --merge-output-format mp4"
alias yt-mp3 "yt-dlp -x --audio-format mp3"
alias yt-mp4 "yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' --merge-output-format mp4"
alias yt-thumbnail "yt-dlp --skip-download --write-thumbnail"
alias yt-info "yt-dlp --skip-download --print-json"
