[style.description]
underline = false
bold = false
italic = false

[style.command_name]
foreground = "yellow"
underline = false
bold = true
italic = false

[style.example_text]
foreground = "white"
underline = false
bold = false
italic = false

[style.example_code]
foreground = "blue"
underline = false
bold = false
italic = false

[style.example_variable]
foreground = "magenta"
underline = true
bold = false
italic = false

[display]
compact = true
use_pager = false

[updates]
auto_update = false

[directories]
