set -gx MCFLY_PROMPT "@"
set -gx MCFLY_LIGHT FALSE
set -gx MCFLY_RESULTS 25
set -gx MCFLY_FUZZY 2
set -gx MCFLY_RESULTS_SORT RANK
set -gx MCFLY_DISABLE_MENU TRUE
set -gx MCFLY_INTERFACE_VIEW TOP
set -gx MCFLY_DELETE_WITHOUT_CONFIRM FALSE